name: Build MRS

on:
  push:
    paths:
      - "emby.list"
      - "scripts/**"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Convert classical list -> sing-box ruleset source JSON
        run: |
          python scripts/list2ruleset.py
          test -f emby-source.json && head -n 20 emby-source.json || true

      - name: Download sing-box
        run: |
          # 选一个稳定版本号；如需更新，改成最新版本即可
          VER="1.8.8"
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v${VER}/sing-box-${VER}-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x ./sing-box
          ./sing-box version

      - name: Compile to emby.mrs
        run: |
          ./sing-box rule-set compile \
            --output emby.mrs \
            --type domain \
            emby-source.json
          ls -lh emby.mrs

      - name: Commit emby.mrs back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update emby.mrs from emby.list"
          file_pattern: "emby-source.json emby.mrs"
